# Generated by Django 3.0.7 on 2023-06-01 02:45

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230601_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='menu_item_model',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_model_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
