# Generated by Django 3.0.7 on 2023-06-01 03:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230601_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='menu_item_photo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_post_path),
        ),
    ]
